config/routes.rb
FobalHero::Application.routes.draw do

  resources :friendships

  resources :stadiums

  post 'notifications/read'

  resources :invitations_to_register, :only => [:create] do
    member do
      get 'accept'
    end
  end

  resources :invitations_to_play, :only => [] do
    member do
      get 'accept'
      get 'decline'
    end
  end

  resources :matches, :except => [:destroy, :edit] do
    member do
      post :notify_changes
      post :invite_to_play
      post :post_comment
      get :comments
      post :i_played, :controller => :surveys
      post :i_didnt_play, :controller => :surveys
      post :i_agree_score, :controller => :surveys
      post :i_dont_agree_score, :controller => :surveys
      post :set_my_goals, :controller => :surveys
      post :set_score, :controller => :surveys
      post :set_stadium_stars, :controller => :surveys

      post :badge, :controller => :match_survey_badges, :action => :create
      delete :badge, :controller => :match_survey_badges, :action => :destroy
    end
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :confirmations => 'confirmations',
    :passwords => 'passwords',
    :registrations => 'registrations'
  }
  resources :users, :only => [:edit, :update, :show]
  match '/admin/users' => 'users#index'
  match 'profile' => 'users#edit'

  devise_scope :user do
    get 'login', :to => 'devise/sessions#new'
    get 'logout', :to => 'devise/sessions#destroy'
  end

  authenticated do
    root :to => 'home#authenticated'
  end

  post 'register', :to => 'home#register'

  root :to => 'home#public'

end

app/models/match.rb
class Match < ActiveRecord::Base
  include FobalHero::Match::Survey
  include FobalHero::Match::Notifications
  include FobalHero::Match::Stadium
  include FobalHero::Match::State
  include FobalHero::Match::User
  include FobalHero::Match::Utils

  MATCH_TYPES = [:five, :seven, :nine, :eleven]
  IMPORTANT_CHANGES = ["play_at","stadium_name"]

  attr_accessible :play_at, :team_one_name, :team_two_name, :match_type, :stadium, :stadium_name

  serialize :match_changes, Hash

  validate :play_at_cant_be_in_the_past

  has_many :invitations_to_play, :dependent => :destroy, :class_name => 'InvitationToPlay' do
    def accepted
      where(:accepted => true)
    end

    def declined
      where(:accepted => false)
    end

    def pending
      where(:accepted => nil)
    end
  end

  has_many :comments, :as => :commentable, :dependent => :destroy

  after_create :create_host_invitation
  before_save :toggle_draft_status, :store_match_changes

  def self.past(user)
    where('matches.play_at < ?', (Time.now - 10.days)).
    joins(:invitations_to_play).
    where('invitations_to_play.user_id = ?', user.id).
    order(:play_at)
  end

  def self.pending_review(user)
    where(:play_at => (Time.now - 10.days)..(Time.now)).
    joins(:invitations_to_play).
    where('invitations_to_play.user_id = ?', user.id).
    where('invitations_to_play.accepted = ?', true).
    order(:play_at)
  end

  def self.upcoming(user)
    match_ids = where("play_at > ?", Time.now).
      where('matches.host_id = ?', user.id).
      pluck('matches.id')

    match_ids << unscoped.joins(:invitations_to_play).
      where('invitations_to_play.user_id = ?', user.id).
      where('matches.play_at > ?', Time.now).
      pluck('matches.id')

    match_ids << unscoped.joins(:invitations_to_play).
      where('invitations_to_play.user_id = ?', user.id).
      where('invitations_to_play.accepted = ?', true).
      where('matches.play_at IS ?', nil).
      pluck('matches.id')

    self.unscoped.where(:id => match_ids.uniq).order(:play_at)
  end

  def self.waiting_response(user)
    self.joins(:invitations_to_play).
      where('invitations_to_play.user_id = ?', user.id).
      where('invitations_to_play.accepted IS ?', nil).
      where('matches.play_at IS ? OR matches.play_at > ?', nil, Time.now).
      order(:play_at)
  end

  def self.next(user)
    self.upcoming(user).order('matches.play_at DESC').limit(1).first
  end

  def self.prev
    where('play_at <= ?', Time.zone.now).order(:play_at).limit(1).first
  end

  def self.draft(user)
    where(:is_draft => true).where(:host_id => user.id).first
  end

  def already_played?
    return false if self.is_draft
    return false if self.play_at.nil?
    return true if self.play_at < Time.now
    false
  end

  def pending_review?
    already_played? and !is_closed?
  end

  def match_type_options_for_select
    MATCH_TYPES.map {|type| [I18n.t(type, :scope => [:activerecord, :attributes, :match, :match_type_values]), type]}
  end

  def is_closed?
    (self.play_at < Time.now - 10.days) rescue false
  end

  def team_one_proposed_score
    all = self.match_surveys.map { |survey| survey.team_one_score }
    proposed_score = 0
    all.uniq.each do |score|
      proposed_score = score if all.count(score) > all.count(proposed_score)
    end
    proposed_score
  end

  def team_two_proposed_score
    all = self.match_surveys.map { |survey| survey.team_two_score }
    proposed_score = 0
    all.uniq.each do |score|
      proposed_score = score if all.count(score) > all.count(proposed_score)
    end
    proposed_score
  end

  def sum_users_goals
    self.match_surveys.inject(0) {|result, survey| survey.goals.nil? ? result : result + survey.goals }
  end

  def number_of_players_in_stadium
    case self.match_type
    when 'five'
      return 10
    when 'seven'
      return 14
    when 'nine'
      return 18
    when 'eleven'
      return 22
    end
  end

private

  def create_host_invitation
    invitation = InvitationToPlay.new
    invitation.match = self
    invitation.host = self.host
    invitation.user = self.host
    invitation.message = "Invitado por ser el organizador"
    invitation.accepted = true
    invitation.save!
    invitation.accepted!
  end

  def toggle_draft_status
    if self.invitations_to_play.accepted.count > 1
      self.is_draft = false
    else
      self.is_draft = true
    end
    return true
  end

  def store_match_changes
    return nil if self.is_draft?
    important_changes = self.changes.select{|key,value| IMPORTANT_CHANGES.include? key}
    self.match_changes = self.match_changes.merge important_changes
    self.match_changes.delete("match_changes")
  end

  def play_at_cant_be_in_the_past
    return true if self.play_at.nil?
    unless self.play_at > Time.now
      errors.add(:play_at, :past_play_at)
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  before_filter :find_match, :find_friends,  :only => [
    :show,
    :edit,
    :update,
    :invite_to_play,
    :notify_changes
  ]
  before_filter :check_match_play_at_is_future, :only => [
    :update,
    :invite_to_play
  ]

  def index
    @recent_matches = Match.pending_review(current_user)
    @upcoming_matches = Match.upcoming(current_user)
    @past_matches = Match.past(current_user)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matches }
    end
  end

  def show
    initialize_comment
  end

  def new
    @match = Match.draft(current_user) || Match.new
    @match.host = current_user
    @match.match_type = @match.match_type || :five
    @match.play_at = Time.now + 2.days
    @match.save!

    respond_to do |format|
      format.html { redirect_to match_path @match }
      format.json { render json: @match }
    end
  end

  def create
    @match = Match.new(params[:match])

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Partido creado' }
        format.json { render json: @match, status: :created, location: @match }
      else
        format.html { render action: "new" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to match_path(@match), notice: 'Cambios guardados' }
        format.json { head :no_content }
        format.js { render :nothing => true }
      else
        format.html { render action: "show" }
        format.js { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def invite_to_play
    @emails = params[:emails].downcase.scan(/\b[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\b/)
    @users = extract_users
    @match = Match.find params[:id]
    @users += User.invite_emails(@emails, current_user)
    InvitationToPlay.invite(@users, @match, current_user, params[:comment])
    @match.save
    render json: @users, :only => [:id, :name], :methods => [:avatar_thumb]
  end

  def post_comment
    @match = Match.find params[:id]
    @comment = Comment.new params[:comment]
    @comment.user = current_user
    @comment.commentable = @match
    @comment.save!

    #TODO not need application notifications just yet
    # @match.notify_comment(@comment)
    respond_to do |format|
      format.html { redirect_to match_path(@match) + "#comment_#{@comment.id}" }
      format.js
    end
  end

  def comments
    @comments = Match.find(params[:id]).comments.older_first
    @comments = @comments.where('comments.id > ?', params[:comment_id]) if params[:comment_id].present?
    @prev_comment = (params[:comment_id].present? ? Comment.find(params[:comment_id]) : @comments.first) rescue @comments.first
    @comment_side = params[:side].present? ? params[:side].to_sym : :left
  end

  def notify_changes

    respond_to do |format|
      if @match.pending_notification? & @match.notify_changes!
        format.html {head :ok}
      else
        format.html {head :bad_request}
      end
    end
  end

private

  def extract_users
    return User.find params[:user_ids].split(",") if params[:user_ids].present?
    return []
  end

  def initialize_comment
    @new_comment = Comment.new
    @new_comment.commentable = @match
    @new_comment.user = current_user
    @comment_side = :left
  end

  def find_match
    @match = Match.find params[:id]
  end

  def check_match_play_at_is_future
    if @match.already_played?
      redirect_to match_path(@match), :flash => {
        error: t(:read_only_match, :scope => [:controllers, :matches])
      }
      return
    end
  end

  def find_friends
    @friends = current_user.friends - @match.users
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_filter :find_match, :find_invitation_to_play, :find_match_survey

  def i_played
    @survey.played = true
    @survey.save
    if proposed_score?
      render 'matches/survey/proposed_score_step', :locals => { :match => @match, :survey => @survey }
    else
      render 'matches/survey/score_step', :locals => { :match => @match, :survey => @survey }
    end
  end

  def i_didnt_play
    @survey.played = false
    @survey.save
    render 'matches/survey/review_step', :locals => { :match => @match, :survey => @survey }
  end

  def i_agree_score
    @survey.team_one_score = @match.team_one_proposed_score
    @survey.team_two_score = @match.team_two_proposed_score

    respond_to do |format|
      if @survey.save
        format.js { render 'matches/survey/goals_step', :locals => { :match => @match, :survey => @survey } }
      else
        format.js { render 'matches/survey/score_step', :locals => { :match => @match, :survey => @survey } }
      end
    end
  end

  def i_dont_agree_score
    render 'matches/survey/score_step', :locals => { :match => @match, :survey => @survey }
  end

  def set_score
    @survey.team_one_score = params[:team_one_score]
    @survey.team_two_score = params[:team_two_score]

    respond_to do |format|
      if @survey.save
        format.js { render 'matches/survey/goals_step', :locals => { :match => @match, :survey => @survey } }
      else
        format.js { render 'matches/survey/score_step', :locals => { :match => @match, :survey => @survey } }
      end
    end
    
  end

  def set_my_goals
    @survey.goals = params[:my_goals] || 0

    respond_to do |format|
      if @survey.save
        format.js { render 'matches/survey/qualify_step', :locals => { :match => @match, :survey => @survey } }
      else
        format.js { render 'matches/survey/goals_step', :locals => { :match => @match, :survey => @survey } }
      end
    end
  end

  def set_stadium_stars
    @survey.stadium_stars = params[:stars] || 1
    @survey.save
    head :ok
  end

private

  def proposed_score?
    (@match.match_surveys - [@survey]).each do |survey|
      return true if survey.team_one_score.present?
    end
    false
  end

  def find_match
    @match = Match.find(params[:id])
  end

  def find_invitation_to_play
    @invitation_to_play = current_user.invitation_to_play(@match)
  end

  def find_match_survey
    @survey = @invitation_to_play.match_survey || @invitation_to_play.create_match_survey
  end
end

app/helpers/matches_helper.rb
module MatchesHelper

  def calculate_comment_side(current_comment, prev_comment)
    return @comment_side if current_comment.user == prev_comment.user
    @comment_side = (@comment_side == :left) ? :right : :left
    @comment_side
  end

  def display_details_for(match = @match)
    presenter = MatchPresenter.new(match, self)
    if block_given?
      yield presenter
    else
      presenter
    end
  end

  def display_survey_for(match = @match)
    presenter = MatchSurveyPresenter.new(match, current_user, self)
    if block_given?
      yield presenter
    else
      presenter
    end
  end

  def display_survey_badges_for(player, survey)
    content_tag :ul, :class => 'badges' do
      badges = "".html_safe
      badges += display_badge(player, survey, :fake_goals)
      badges += display_badge(player, survey, :yellow_card)
      badges += display_badge(player, survey, :red_card)
      badges += display_badge(player, survey, :doping)
      badges += display_badge(player, survey, :man_of_the_match)
      badges += display_badge(player, survey, :cold_chest)
      badges += display_badge(player, survey, :betrayer)
      badges
    end
  end

  def display_badge(player, survey, type)
    if type.to_sym == :fake_goals
      display_fake_goals_badge(player, survey)
    else
      did_vote_badge = survey.did_vote_badge_for_player?(type, player, [current_user])
      someone_voted_badge = survey.invitation_to_play.match.someone_voted_badge_for_player?(type, player, [current_user])
      content_tag :li, :class => "#{type.to_s.gsub('_', '-')}#{' voted' if did_vote_badge}#{' other-voted' if someone_voted_badge}#{' disabled' unless someone_voted_badge or did_vote_badge}" do
        link_to "", badge_match_path(survey.invitation_to_play.match, :type => type, :player_id => player.id), :method => (did_vote_badge ? :delete : :post), :remote => true, :title => t(type, :scope => [:badges])
      end
    end
  end

  def display_fake_goals_badge(player, survey)
    player_survey = MatchSurvey.by_user(player).by_match(survey.match).first
    return if player_survey.nil?
    return if player_survey.goals.nil?
    return unless player_survey.goals > 0
    did_vote_badge = survey.did_vote_badge_for_player?(:fake_goals, player, [current_user])
    someone_voted_badge = survey.invitation_to_play.match.someone_voted_badge_for_player?(:fake_goals, player, [current_user])
    content_tag :li, :class => "fake-goals#{' voted' if did_vote_badge}#{' other-voted' if someone_voted_badge}#{' disabled' unless someone_voted_badge or did_vote_badge}" do
      link_to player_survey.goals.to_s, badge_match_path(survey.invitation_to_play.match, :type => :fake_goals, :player_id => player.id), :method => (did_vote_badge ? :delete : :post), :remote => true, :title => t(:fake_goals, :scope => [:badges])
    end
  end

  def match_state(match)
    return "Cerrado" if match.is_closed?
    return "Evaluando resultado" if match.already_played?
    return "No definido" if match.play_at.nil?
    return "Por jugar"
  end

  def editable_stadium_field(name, object)
    raise "Method deprecated"
    resource_name = object.class.to_s.underscore

    content = content_tag(:span, :class => (object[name].present? ? "visible" : "hidden") + " editable-label") do
      link_to_unless object.stadium.nil?, object[name], hash_for_stadium_path(:id => object.stadium)
    end +
    content_tag(:span, :class => (object[name].present? ? "hidden" : "visible") + " editable-field") do
      text_field_tag("#{resource_name}[#{name}]", nil, :class => "input-mini", :data => { :provide => "typeahead", :items => "4", :source => stadiums_for_select.to_s }, :autocomplete => 'off')
    end
    content.html_safe
  end

  def stadiums_for_select
    Stadium.pluck(:name)
  end

  def match_date(match)
    return "Sin fecha" if match.play_at.nil?
    return l(match.play_at.to_date, :format => :short)
  end
end

app/views/matches/survey/_goals_step.html.erb
<div class="wrapper goals-step">
  <div class="title review">
    <h2><%= t :rate, :scope => [:messages, :match] %></h2>
  </div>

  <div class="input">
    <div class="question">
      <h3><%= t :your_goals, :scope => [:questions, :match] %></h3>
    </div>

    <table class="match-score">
      <tr>
        <td>Goles del partido</td>
        <td class="total-score"><%= @match.team_one_proposed_score + @match.team_two_proposed_score %></td>
      </tr>
      <tr>
        <td>Goles restantes</td>
        <td class="score"><%= (@match.team_one_proposed_score + @match.team_two_proposed_score) - @match.sum_users_goals %></td>
      </tr>
    </table>

    <div class="my-goals">
      <%= form_tag set_my_goals_match_path(match), :remote => true do |f| %>
        <p>Yo hice <%= number_field_tag :my_goals, 0 %> Goles <%= submit_tag("OK") %></p>
      <% end -%>
      <p>Yo <%= link_to "No Hice", set_my_goals_match_path(match),  :remote => true, :method => :post, :class => "no-goals" %> Goles.</p>
    </div>
  </div>

  <div class="info">
    <h4>Goles de tus amigos</h4>
    <table class="table players-list">
      <% (match.users.going - [current_user]).each do |player| %>
        <tr>
          <td class="avatar"><%= image_tag player.avatar.url(:mini) %></td>
          <td class="name"><%= player.name %></td>
          <td class="score"><%= player.goals(match) %></td>
          <td class="fake-score">
            <ul class="badges">
              <%= display_badge(player, survey, :fake_goals) %>
            </ul>
          </td>
        </tr>
      <% end -%>
    </table>
    <div class="steps-help">En caso de que los goles sean falsos, denuncia al jugador presionando sobre el numero.<br/> Ej: <div class="icn-denounce"></div></div>
  </div>
</div>

app/views/matches/survey/_played_step.html.erb
<div class="wrapper played-step">
  <div class="title review">
    <h2><%= t :rate, :scope => [:messages, :match] %></h2>
  </div>

  <div class="input">
    <div class="question">
      <h3><span class="left-arrow"></span> <%= t :did_you_play, :scope => [:questions, :match] %></h3>
    </div>

    <div class="yes">
      <%= link_to t(:yes, :scope => [:actions]), i_played_match_path(match), :remote => true, :method => :post %>
    </div>

    <div class="no">
      <%= link_to t(:no, :scope => [:actions]), i_didnt_play_match_path(match), :remote => true, :method => :post %>
    </div>
  </div>
</div>

app/views/matches/survey/_proposed_score_step.html.erb
<div class="wrapper proposed-score-step">
  <div class="title review">
    <h2><%= t :rate, :scope => [:messages, :match] %></h2>
  </div>

  <div class="input">
    <div class="question">
      <h3><%= t :agree_with_score, :scope => [:questions, :match] %></h3>
    </div>

    <table class="proposed-score table">
      <tbody>
        <tr class="score team-one-score">
          <td class="shield"><%= image_tag 'shields/shield_01.png' %></td>
          <td class="team-name"><%= match.team_one_name %></td>
          <td class="team-score"><%= match.team_one_proposed_score %></td>
        </tr>
        <tr class="score team-two-score">
          <td class="shield"><%= image_tag 'shields/shield_02.png' %></td>
          <td class="team-name"><%= match.team_two_name %></td>
          <td class="team-score"><%= match.team_two_proposed_score %></td>
        </tr>
      </tbody>
    </table>
    
    <div class="choice">
    <div class="yes">
      <%= link_to t(:yes, :scope => [:actions]), i_agree_score_match_path(match), :remote => true, :method => :post %>
    </div>

    <div class="no">
      <%= link_to t(:no, :scope => [:actions]), i_dont_agree_score_match_path(match), :remote => true, :method => :post %>
    </div>
    </div>
  </div>

  <div class="info">
    <h4>Resultado segun tus amigos:</h4>
    <table class="table players-list">
      <tr>
        <td colspan="2" class="team-name">Jugador</td>
        <td class="shield"><%= image_tag 'shields/shield_01.png' %></td>
        <td class="shield"><%= image_tag 'shields/shield_02.png' %></td>
      </tr>
      <% (match.match_surveys - [survey]).each do |current_survey| %>
        <tr>
          <td class="avatar"><%= image_tag current_survey.invitation_to_play.user_avatar.url(:mini) %></td>
          <td class="name"><%= current_survey.invitation_to_play.user_name %></td>
          <td class="team-score"><%= current_survey.team_one_score %></td>
          <td class="team-score"><%= current_survey.team_two_score %></td>
        </tr>
      <% end -%>
    </table>
  </div>
</div>

app/views/matches/survey/_qualify_step.html.erb
<div class="wrapper qualify-step">
  <div class="title review">
    <h2><%= t :rate, :scope => [:messages, :match] %></h2>
  </div>

  <div class="info">
    <h4><%= t :qualify, :scope => [:questions, :match] %></h4>
    <div class="steps-help">Presione sobre los iconos para calificar.</div>
    <div class="stadium">
      <h5><%= match.stadium_name %></h5>
      <ul class="stars horizontal unstyled">
        <% (1..5).each do |index| %>
          <li class="star<%= " active" if survey.stadium_stars.to_i >= index -%>"><%= link_to '', set_stadium_stars_match_path(match, {:stars => index}), :method => :post, :remote => true %></li>
        <% end %>
      </ul>
    </div>

    <table class="table players-list">
      <% (match.users.going - [current_user]).each do |player| %>
        <tr>
          <td class="avatar"><%= image_tag player.avatar.url(:mini) %></td>
          <td class="name"><%= player.name %></td>
          <td class="badges"><%= display_survey_badges_for(player, survey) %></td>
        </tr>
      <% end -%>
    </table>

    <h4><%= t :badges, :scope => [:messages, :match] %></h4>
    <ul class="badges labels" >
      <% %w(fake-goals yellow-card red-card doping man-of-the-match cold-chest betrayer).each do |badge| %>
        <li class="<%= badge %> voted"><%= t(badge.underscore, :scope => [:badges])%></li>
      <% end -%>
    </ul>
  </div>
</div>

app/views/matches/survey/_review_step.html.erb
<div class="wrapper review-step">
  <div class="title review">
    <h2><%= t :review, :scope => [:messages, :match] %></h2>
  </div>

  <div class="info">
    <h4>Resultado del partido</h4>
    <table class="table match-score">
      <tbody>
        <tr>
          <td class="shield"><%= image_tag 'shields/shield_01.png' %></td>
          <td class="name"><%= match.team_one_name %></td>
          <td class="score"><%= match.team_one_proposed_score %></td>
        </tr>
         <tr>
          <td class="shield"><%= image_tag 'shields/shield_02.png' %></td>
          <td class="name"><%= match.team_two_name %></td>
          <td class="score"><%= match.team_two_proposed_score %></td>
        </tr>
      </tbody>
    </table>

    <table class="table players-list">
      <% match.users.going.each do |player| %>
        <tr>
          <td class="avatar"><%= image_tag player.avatar.url(:mini) %></td>
          <td class="name"><%= player.name %></td>
          <td class="badges"><%= display_badges_for(player, match) %></td>
        </tr>
      <% end -%>
    </table>

    <h4><%= t :badges, :scope => [:messages, :match] %></h4>
    <ul class="badges labels" >
      <% %w(goals fake-goals yellow-card red-card doping man-of-the-match cold-chest betrayer).each do |badge| %>
        <li class="<%= badge %> voted"><%= t(badge.underscore, :scope => [:badges])%></li>
      <% end -%>
    </ul>
  </div>
</div>

app/views/matches/survey/_score_step.html.erb
<div class="wrapper score-step">
  <div class="title review">
    <h2><%= t :rate, :scope => [:messages, :match] %></h2>
  </div>

  <div class="input">
    <div class="question">
      <h3><%= t :set_score, :scope => [:questions, :match] %></h3>
    </div>

    <%= form_tag(set_score_match_path, :id => 'set_score_form', :remote => true) do %>
      <table class="proposed-score table">
        <tbody>
          <tr class="score team-one-score">
            <td class="shield"><%= image_tag 'shields/shield_01.png' %></td>
            <td class="team-name"><%= match.team_one_name %></td>
            <td class="team-score"><%= number_field_tag(:team_one_score, match.team_one_proposed_score) %></td>
          </tr>
          <tr class="score team-two-score">
            <td class="shield"><%= image_tag 'shields/shield_02.png' %></td>
            <td class="team-name"><%= match.team_two_name %></td>
            <td class="team-score"><%= number_field_tag(:team_two_score, match.team_two_proposed_score) %></td>
          </tr>
        </tbody>
      </table>
      <%= submit_tag("Ok", :class => 'btn') %>
    <% end %>
  </div>

  <div class="info">
    <h4>Resultado segun tus amigos:</h4>
    <table class="table players-list">
      <tr>
        <td colspan="2" class="team-name">Jugador</td>
        <td class="shield"><%= image_tag 'shields/shield_01.png' %></td>
        <td class="shield"><%= image_tag 'shields/shield_02.png' %></td>
      </tr>
      <% (match.match_surveys - [survey]).each do |current_survey| %>
        <tr>
          <td class="avatar"><%= image_tag current_survey.invitation_to_play.user_avatar.url(:mini) %></td>
          <td class="name"><%= current_survey.invitation_to_play.user_name %></td>
          <td class="team-score"><%= current_survey.team_one_score %></td>
          <td class="team-score"><%= current_survey.team_two_score %></td>
        </tr>
      <% end -%>
    </table>
  </div>
</div>

app/views/matches/survey/goals_step.js.erb
$('#survey_container').slideUp(function(){
  $('#survey_container').html("<%=j raw(render(:partial => 'matches/survey/goals_step', :locals => { :match => @match, :survey => @survey })) %>");
  $('#survey_container').slideDown();
});

app/views/matches/survey/proposed_score_step.js.erb
$('#survey_container').slideUp(function(){
  $('#survey_container').html("<%=j raw(render(:partial => 'matches/survey/proposed_score_step', :locals => { :match => match, :survey => survey })) %>");
  $('#survey_container').slideDown();
});

app/views/matches/survey/qualify_step.js.erb
$('#survey_container').slideUp(function(){
  $('#survey_container').html("<%=j raw(render(:partial => 'matches/survey/qualify_step', :locals => { :match => match, :survey => survey })) %>");
  $('#survey_container').slideDown();
});

app/views/matches/survey/review_step.js.erb
$('#survey_container').slideUp(function(){
  $('#survey_container').html("<%=j raw(render(:partial => 'matches/survey/review_step', :locals => { :match => match, :survey => survey })) %>");
  $('#survey_container').slideDown();
});

app/views/matches/survey/score_step.js.erb
$('#survey_container').slideUp(function(){
  $('#survey_container').html("<%=j raw(render(:partial => 'matches/survey/score_step', :locals => { :match => match, :survey => survey })) %>");
  $('#survey_container').slideDown();
});

app/views/matches/survey/set_score.js.erb
$('#survey_container').slideUp(function(){
  $('#survey_container').html("<%=j raw(render(:partial => 'matches/survey/goals_step', :locals => { :match => match, :survey => survey })) %>");
  $('#survey_container').slideDown();
});