config/routes.rb
FobalHero::Application.routes.draw do

  resources :friendships

  resources :stadiums

  post 'notifications/read'

  resources :invitations_to_register, :only => [:create] do
    member do
      get 'accept'
    end
  end

  resources :invitations_to_play, :only => [] do
    member do
      get 'accept'
      get 'decline'
    end
  end

  resources :matches, :except => [:destroy, :edit] do
    member do
      post :notify_changes
      post :invite_to_play
      post :post_comment
      get :comments
      post :i_played, :controller => :surveys
      post :i_didnt_play, :controller => :surveys
      post :i_agree_score, :controller => :surveys
      post :i_dont_agree_score, :controller => :surveys
      post :set_my_goals, :controller => :surveys
      post :set_score, :controller => :surveys
      post :set_stadium_stars, :controller => :surveys

      post :badge, :controller => :match_survey_badges, :action => :create
      delete :badge, :controller => :match_survey_badges, :action => :destroy
    end
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :confirmations => 'confirmations',
    :passwords => 'passwords',
    :registrations => 'registrations'
  }
  resources :users, :only => [:edit, :update, :show]
  match '/admin/users' => 'users#index'
  match 'profile' => 'users#edit'

  devise_scope :user do
    get 'login', :to => 'devise/sessions#new'
    get 'logout', :to => 'devise/sessions#destroy'
  end

  authenticated do
    root :to => 'home#authenticated'
  end

  post 'register', :to => 'home#register'

  root :to => 'home#public'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :authenticate_user!, :except => [:public, :register]

	def public
    @new_user = User.new
  end

  def authenticated
  end

  def register
		@new_user = User.new
    @new_user.email = params[:user][:email] if params[:user] and params[:user][:email]
    @new_user.password = params[:user][:password] if params[:user] and params[:user][:password]
    @new_user.password_confirmation = @new_user.password

    respond_to do |format|
      if @new_user.save
        format.html { redirect_to root_path, notice: I18n.t(:signed_up_but_unconfirmed, :scope => [:devise, :registrations]) }
        format.json { render json: @new_user, status: :created, location: @new_user }
      else
        format.html { render action: "public" }
        format.json { render json: @new_user.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/authenticated.html.erb
<div class="row">
  <div class="span4 offset1">
    <%= link_to image_tag("logo_334.png"), root_path %>
  </div>
  <div class="span4">
    <h2>CONVERTITE EN UN <b>HEROE DEL FUTBOL</b></h2>
    <h1>JUGA AL FUTBOL</h1>
  </div>
</div>

<div class="row">
  <div class="span4 offset1">
    <%= link_to "Mis Partidos", matches_path, :class => "btn-home match" %>
  </div>
  <div class="span4">
    <%= link_to new_match_path, :class => "new-match-btn" do %>
      <div class="icon"></div>
      <%= t(:new_match, :scope => [:actions]) %>
    <% end %>
  </div>
</div>

app/views/home/public.html.erb
<div class="row">

  <div class="login-wrapper"><!--LOGIN WRAPPER-->
    <div class="span3">
      <div class="logo">
        <%= image_tag "login/logo_220.png" %>
      </div>
    </div>
    <div class="span9">
      <div class="top-title">
        <h2>CONTROL MAESTRO DEL FUTBOL</h2>
      </div>
    </div>

    <div class="span12">
      <div class="separator-line"></div>
    </div>


    <div class="span6">
      <div class="welcome">
        <h3>BIENVENIDOS A FOBAL HERO</h3>
        <p>Registratre como usuario, invitá a tus amigos y organizá partidos de futbol online, para luego jugarlos en el mundo real.</p>
      </div>
    </div>

    <div class="span6">
      <div class="title-login-box">
      <h3>Registrate como jugador</h3>
      </div>
      <div class="login-box"><!--LOGIN BOX-->
        <div class="register fb">
          Queres ser feliz? <%= link_to "Registrate con Facebook", user_omniauth_authorize_path(:facebook), :class => "btn-fb" %>
        </div>
        <div class="separator-line"></div>
        <div class="register mail">
          También podes registrarte usando tu e-mail:
          <%= simple_form_for(@new_user, :url => register_path, :html => { :class => 'registration-form form-inline', :autocomplete => 'off' }) do |f| %>
            <%= f.input :email, :label => false, :placeholder => User.human_attribute_name(:email) %>
            <%= f.input :password, :label => false, :placeholder => User.human_attribute_name(:password) %>
            <div class="register-bottom">
              <span>
                Una vez registrado, podés completar tu perfil de jugador.<br />
                <%= link_to t(:no_confirmation_instructions, :scope => [:devise, :sessions]), new_confirmation_path(:user) %>
              </span>
              <%= f.submit "Registrate", :class => 'btn btn-primary pull-right' %>
            </div>
          <% end %>
        </div>
      </div><!--END LOGIN BOX-->
      <div class="footer-login"><h4>TE GUSTA <strong>FOBAL HERO</strong>?</h4> me gusta - g+1</div>
    </div>


    <div class="span12">
      <div class="separator-line"></div>
    </div>

    <!--BLOQUE INFO QUE HACER-->
    <div class="span6">
      <div class="box-info">
        <h3>Que podés hacer en <strong>Fobal Hero</strong>?</h3>
        <div class="detail one">
          <%= image_tag "login/graf_icn_ptmc_1.png" %>
        <ul>
          <li>Registrarte como jugador</li>
          <li>Organizar un partido</li>
          <li>Crear tu equipo - <strong>proximamente</strong></li>
          <li>Participar de un Campeonato - <strong>proximamente</strong></li>
        </ul>
        </div>
      </div>
    </div>

    <!--BLOQUE INFO PARTIDO-->
    <div class="span6">
      <div class="box-info">
        <h3>Ya estas registrado? <strong>Organizá un partido</strong>.</h3>
        <div class="detail two">
          <p>Invitá a tus amigos y completá el equipo.</p>
        </div>
      </div>
    </div>

    <!--BLOQUE INFO CALIFICAR-->
    <div class="span6">
      <div class="box-info">
        <h3>Ya jugaste? Calificá el <strong>partido</strong> y los <strong>jugadores</strong>.</h3>
        <div class="detail three">
          <%= image_tag "login/graf_qualify.png" %>
        </div>
      </div>
    </div>

    <!--BLOQUE INFO COMENTAR-->
    <div class="span6">
      <div class="box-info">
        <h3>Comentá <strong>antes y despues</strong> del partido.</h3>
        <div class="detail four">
          <%= image_tag "login/graf_chat.png" %>
        </div>
      </div>
    </div>


    

  </div><!--END LOGIN WRAPPER-->	
</div>

<% content_for :under_content do %>
  <div class="bar-grass"></div>
<%end%>