config/routes.rb
FobalHero::Application.routes.draw do

  resources :friendships

  resources :stadiums

  post 'notifications/read'

  resources :invitations_to_register, :only => [:create] do
    member do
      get 'accept'
    end
  end

  resources :invitations_to_play, :only => [] do
    member do
      get 'accept'
      get 'decline'
    end
  end

  resources :matches, :except => [:destroy, :edit] do
    member do
      post :notify_changes
      post :invite_to_play
      post :post_comment
      get :comments
      post :i_played, :controller => :surveys
      post :i_didnt_play, :controller => :surveys
      post :i_agree_score, :controller => :surveys
      post :i_dont_agree_score, :controller => :surveys
      post :set_my_goals, :controller => :surveys
      post :set_score, :controller => :surveys
      post :set_stadium_stars, :controller => :surveys

      post :badge, :controller => :match_survey_badges, :action => :create
      delete :badge, :controller => :match_survey_badges, :action => :destroy
    end
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :confirmations => 'confirmations',
    :passwords => 'passwords',
    :registrations => 'registrations'
  }
  resources :users, :only => [:edit, :update, :show]
  match '/admin/users' => 'users#index'
  match 'profile' => 'users#edit'

  devise_scope :user do
    get 'login', :to => 'devise/sessions#new'
    get 'logout', :to => 'devise/sessions#destroy'
  end

  authenticated do
    root :to => 'home#authenticated'
  end

  post 'register', :to => 'home#register'

  root :to => 'home#public'

end

app/models/match.rb
class Match < ActiveRecord::Base
  include FobalHero::Match::Survey
  include FobalHero::Match::Notifications
  include FobalHero::Match::Stadium
  include FobalHero::Match::State
  include FobalHero::Match::User
  include FobalHero::Match::Utils

  MATCH_TYPES = [:five, :seven, :nine, :eleven]
  IMPORTANT_CHANGES = ["play_at","stadium_name"]

  attr_accessible :play_at, :team_one_name, :team_two_name, :match_type, :stadium, :stadium_name

  serialize :match_changes, Hash

  validate :play_at_cant_be_in_the_past

  has_many :invitations_to_play, :dependent => :destroy, :class_name => 'InvitationToPlay' do
    def accepted
      where(:accepted => true)
    end

    def declined
      where(:accepted => false)
    end

    def pending
      where(:accepted => nil)
    end
  end

  has_many :comments, :as => :commentable, :dependent => :destroy

  after_create :create_host_invitation
  before_save :toggle_draft_status, :store_match_changes

  def self.past(user)
    where('matches.play_at < ?', (Time.now - 10.days)).
    joins(:invitations_to_play).
    where('invitations_to_play.user_id = ?', user.id).
    order(:play_at)
  end

  def self.pending_review(user)
    where(:play_at => (Time.now - 10.days)..(Time.now)).
    joins(:invitations_to_play).
    where('invitations_to_play.user_id = ?', user.id).
    where('invitations_to_play.accepted = ?', true).
    order(:play_at)
  end

  def self.upcoming(user)
    match_ids = where("play_at > ?", Time.now).
      where('matches.host_id = ?', user.id).
      pluck('matches.id')

    match_ids << unscoped.joins(:invitations_to_play).
      where('invitations_to_play.user_id = ?', user.id).
      where('matches.play_at > ?', Time.now).
      pluck('matches.id')

    match_ids << unscoped.joins(:invitations_to_play).
      where('invitations_to_play.user_id = ?', user.id).
      where('invitations_to_play.accepted = ?', true).
      where('matches.play_at IS ?', nil).
      pluck('matches.id')

    self.unscoped.where(:id => match_ids.uniq).order(:play_at)
  end

  def self.waiting_response(user)
    self.joins(:invitations_to_play).
      where('invitations_to_play.user_id = ?', user.id).
      where('invitations_to_play.accepted IS ?', nil).
      where('matches.play_at IS ? OR matches.play_at > ?', nil, Time.now).
      order(:play_at)
  end

  def self.next(user)
    self.upcoming(user).order('matches.play_at DESC').limit(1).first
  end

  def self.prev
    where('play_at <= ?', Time.zone.now).order(:play_at).limit(1).first
  end

  def self.draft(user)
    where(:is_draft => true).where(:host_id => user.id).first
  end

  def already_played?
    return false if self.is_draft
    return false if self.play_at.nil?
    return true if self.play_at < Time.now
    false
  end

  def pending_review?
    already_played? and !is_closed?
  end

  def match_type_options_for_select
    MATCH_TYPES.map {|type| [I18n.t(type, :scope => [:activerecord, :attributes, :match, :match_type_values]), type]}
  end

  def is_closed?
    (self.play_at < Time.now - 10.days) rescue false
  end

  def team_one_proposed_score
    all = self.match_surveys.map { |survey| survey.team_one_score }
    proposed_score = 0
    all.uniq.each do |score|
      proposed_score = score if all.count(score) > all.count(proposed_score)
    end
    proposed_score
  end

  def team_two_proposed_score
    all = self.match_surveys.map { |survey| survey.team_two_score }
    proposed_score = 0
    all.uniq.each do |score|
      proposed_score = score if all.count(score) > all.count(proposed_score)
    end
    proposed_score
  end

  def sum_users_goals
    self.match_surveys.inject(0) {|result, survey| survey.goals.nil? ? result : result + survey.goals }
  end

  def number_of_players_in_stadium
    case self.match_type
    when 'five'
      return 10
    when 'seven'
      return 14
    when 'nine'
      return 18
    when 'eleven'
      return 22
    end
  end

private

  def create_host_invitation
    invitation = InvitationToPlay.new
    invitation.match = self
    invitation.host = self.host
    invitation.user = self.host
    invitation.message = "Invitado por ser el organizador"
    invitation.accepted = true
    invitation.save!
    invitation.accepted!
  end

  def toggle_draft_status
    if self.invitations_to_play.accepted.count > 1
      self.is_draft = false
    else
      self.is_draft = true
    end
    return true
  end

  def store_match_changes
    return nil if self.is_draft?
    important_changes = self.changes.select{|key,value| IMPORTANT_CHANGES.include? key}
    self.match_changes = self.match_changes.merge important_changes
    self.match_changes.delete("match_changes")
  end

  def play_at_cant_be_in_the_past
    return true if self.play_at.nil?
    unless self.play_at > Time.now
      errors.add(:play_at, :past_play_at)
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  before_filter :find_match, :find_friends,  :only => [
    :show,
    :edit,
    :update,
    :invite_to_play,
    :notify_changes
  ]
  before_filter :check_match_play_at_is_future, :only => [
    :update,
    :invite_to_play
  ]

  def index
    @recent_matches = Match.pending_review(current_user)
    @upcoming_matches = Match.upcoming(current_user)
    @past_matches = Match.past(current_user)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matches }
    end
  end

  def show
    initialize_comment
  end

  def new
    @match = Match.draft(current_user) || Match.new
    @match.host = current_user
    @match.match_type = @match.match_type || :five
    @match.play_at = Time.now + 2.days
    @match.save!

    respond_to do |format|
      format.html { redirect_to match_path @match }
      format.json { render json: @match }
    end
  end

  def create
    @match = Match.new(params[:match])

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Partido creado' }
        format.json { render json: @match, status: :created, location: @match }
      else
        format.html { render action: "new" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to match_path(@match), notice: 'Cambios guardados' }
        format.json { head :no_content }
        format.js { render :nothing => true }
      else
        format.html { render action: "show" }
        format.js { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def invite_to_play
    @emails = params[:emails].downcase.scan(/\b[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\b/)
    @users = extract_users
    @match = Match.find params[:id]
    @users += User.invite_emails(@emails, current_user)
    InvitationToPlay.invite(@users, @match, current_user, params[:comment])
    @match.save
    render json: @users, :only => [:id, :name], :methods => [:avatar_thumb]
  end

  def post_comment
    @match = Match.find params[:id]
    @comment = Comment.new params[:comment]
    @comment.user = current_user
    @comment.commentable = @match
    @comment.save!

    #TODO not need application notifications just yet
    # @match.notify_comment(@comment)
    respond_to do |format|
      format.html { redirect_to match_path(@match) + "#comment_#{@comment.id}" }
      format.js
    end
  end

  def comments
    @comments = Match.find(params[:id]).comments.older_first
    @comments = @comments.where('comments.id > ?', params[:comment_id]) if params[:comment_id].present?
    @prev_comment = (params[:comment_id].present? ? Comment.find(params[:comment_id]) : @comments.first) rescue @comments.first
    @comment_side = params[:side].present? ? params[:side].to_sym : :left
  end

  def notify_changes

    respond_to do |format|
      if @match.pending_notification? & @match.notify_changes!
        format.html {head :ok}
      else
        format.html {head :bad_request}
      end
    end
  end

private

  def extract_users
    return User.find params[:user_ids].split(",") if params[:user_ids].present?
    return []
  end

  def initialize_comment
    @new_comment = Comment.new
    @new_comment.commentable = @match
    @new_comment.user = current_user
    @comment_side = :left
  end

  def find_match
    @match = Match.find params[:id]
  end

  def check_match_play_at_is_future
    if @match.already_played?
      redirect_to match_path(@match), :flash => {
        error: t(:read_only_match, :scope => [:controllers, :matches])
      }
      return
    end
  end

  def find_friends
    @friends = current_user.friends - @match.users
  end
end

app/helpers/matches_helper.rb
module MatchesHelper

  def calculate_comment_side(current_comment, prev_comment)
    return @comment_side if current_comment.user == prev_comment.user
    @comment_side = (@comment_side == :left) ? :right : :left
    @comment_side
  end

  def display_details_for(match = @match)
    presenter = MatchPresenter.new(match, self)
    if block_given?
      yield presenter
    else
      presenter
    end
  end

  def display_survey_for(match = @match)
    presenter = MatchSurveyPresenter.new(match, current_user, self)
    if block_given?
      yield presenter
    else
      presenter
    end
  end

  def display_survey_badges_for(player, survey)
    content_tag :ul, :class => 'badges' do
      badges = "".html_safe
      badges += display_badge(player, survey, :fake_goals)
      badges += display_badge(player, survey, :yellow_card)
      badges += display_badge(player, survey, :red_card)
      badges += display_badge(player, survey, :doping)
      badges += display_badge(player, survey, :man_of_the_match)
      badges += display_badge(player, survey, :cold_chest)
      badges += display_badge(player, survey, :betrayer)
      badges
    end
  end

  def display_badge(player, survey, type)
    if type.to_sym == :fake_goals
      display_fake_goals_badge(player, survey)
    else
      did_vote_badge = survey.did_vote_badge_for_player?(type, player, [current_user])
      someone_voted_badge = survey.invitation_to_play.match.someone_voted_badge_for_player?(type, player, [current_user])
      content_tag :li, :class => "#{type.to_s.gsub('_', '-')}#{' voted' if did_vote_badge}#{' other-voted' if someone_voted_badge}#{' disabled' unless someone_voted_badge or did_vote_badge}" do
        link_to "", badge_match_path(survey.invitation_to_play.match, :type => type, :player_id => player.id), :method => (did_vote_badge ? :delete : :post), :remote => true, :title => t(type, :scope => [:badges])
      end
    end
  end

  def display_fake_goals_badge(player, survey)
    player_survey = MatchSurvey.by_user(player).by_match(survey.match).first
    return if player_survey.nil?
    return if player_survey.goals.nil?
    return unless player_survey.goals > 0
    did_vote_badge = survey.did_vote_badge_for_player?(:fake_goals, player, [current_user])
    someone_voted_badge = survey.invitation_to_play.match.someone_voted_badge_for_player?(:fake_goals, player, [current_user])
    content_tag :li, :class => "fake-goals#{' voted' if did_vote_badge}#{' other-voted' if someone_voted_badge}#{' disabled' unless someone_voted_badge or did_vote_badge}" do
      link_to player_survey.goals.to_s, badge_match_path(survey.invitation_to_play.match, :type => :fake_goals, :player_id => player.id), :method => (did_vote_badge ? :delete : :post), :remote => true, :title => t(:fake_goals, :scope => [:badges])
    end
  end

  def match_state(match)
    return "Cerrado" if match.is_closed?
    return "Evaluando resultado" if match.already_played?
    return "No definido" if match.play_at.nil?
    return "Por jugar"
  end

  def editable_stadium_field(name, object)
    raise "Method deprecated"
    resource_name = object.class.to_s.underscore

    content = content_tag(:span, :class => (object[name].present? ? "visible" : "hidden") + " editable-label") do
      link_to_unless object.stadium.nil?, object[name], hash_for_stadium_path(:id => object.stadium)
    end +
    content_tag(:span, :class => (object[name].present? ? "hidden" : "visible") + " editable-field") do
      text_field_tag("#{resource_name}[#{name}]", nil, :class => "input-mini", :data => { :provide => "typeahead", :items => "4", :source => stadiums_for_select.to_s }, :autocomplete => 'off')
    end
    content.html_safe
  end

  def stadiums_for_select
    Stadium.pluck(:name)
  end

  def match_date(match)
    return "Sin fecha" if match.play_at.nil?
    return l(match.play_at.to_date, :format => :short)
  end
end

app/views/matches/_comment.html.erb
<div class="row">
  <div id="comment_<%= comment.id %>" class="comment <%= comment_side %>" data-id="<%= comment.id %>" data-side="<%= comment_side %>">
    <div class="avatar">
      <%= image_tag(comment.user.avatar.url(:thumb)) %>
    </div>
    <div class="span8">
      <div class="comment-created-at <%= comment_side %>"><%= time_ago_in_words comment.created_at %></div>
      <div class="box-comment">
      <div class="comment-arrow"></div>
      <div class="comment-user">
        <%= link_to comment.user.name, comment.user %>
      </div>
      <pre class="comment-body"><%= comment.body %></pre>
      </div>
    </div>
  </div>
</div>

app/views/matches/_details.html.erb
<div class="span9">
  <div class="match-details">
    <div class="match-type">
      <span class="type editable">
        <%= Match.human_attribute_name :match_type %>:
        <%= match.match_type %>
      </span>
    </div>
    <div class="match-date">
      <span class="play-at-date editable">
        <%= Match.human_attribute_name :play_at_date %>:
        <%= match.play_at_date %>
      </span>
    </div>
    <div class="match-time">
      <span class="play-at-time editable">
        <%= Match.human_attribute_name :play_at_time %>:
        <%= match.play_at_time %>
      </span>
    </div>
    <div class="match-stadium-name">
      <span class="stadium-name editable">
        <%= Match.human_attribute_name :stadium_name %>:
        <%= match.stadium_name %>
      </span>
    </div>
  </div>
</div>

<div class="span9">
  <div class="teams">
    <div class="team-one">
      <span class="score">
        <%= match.team_one_proposed_score %>
      </span>
      <span class="name editable">
        <%= match.team_one_name %>
      </span>
    </div>
    <div class="team-two">
      <span class="score">
        <%= match.team_two_proposed_score %>
      </span>
      <span class="name editable">
        <%= match.team_two_name %>
      </span>
    </div>
  </div>
</div>

app/views/matches/_friends_list.html.erb
<div class="wrapper friends">
  <div class="title player34">
    <h2><%= User.human_attribute_name :friends %></h2>
  </div>
  <ul id="friends_list" class="friends unstyled">
    <% @friends.each do |user| %>
      <li class="user" id="sidebar_user_<%= user.id %>" data-user-id="<%= user.id %>" data-thumb="<%= user.avatar.url(:thumb) %>">
        <label>
          <%= link_to image_tag(user.avatar.url(:mini), :class => 'mini'), user, :target => :blank %>
          <span class="user-name"><%= user.name %></span>
          <input data-user-id="<%= user.id %>" type="checkbox" class="select">
        </label>
      </li>
    <% end %>
  </ul>
  <div class="box-footer">
    <%= link_to t(:invite, :scope => [:buttons]), '#', :id => 'invite_button', :class => 'btn' %>
  </div>
</div>

app/views/matches/_invite_to_play_popup.html.erb
<div id="invite_friends_modal" class="popup modal fade" tabindex="-1" role="dialog" aria-labelledby="invite_friends_to_play_label" aria-hidden="true">
  <div id="invite_friends_form_result_wrapper">
    <%= render :partial => 'thanks_for_invite_to_play' %>
  </div>
  <div id="invite_friends_form_wrapper">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
      <h3 id="invite_friends_to_play_label"><%= t :invite_to_play, :scope => [:titles, :match] %></h3>
    </div>
    <%= simple_form_for :invite, :url => invite_to_play_match_path, :html => { :id => 'invite_to_play' } do |f| %>
      <div class="modal-body">
        <h5>Lista de amigos seleccionados:</h5>
        <ul class="users-to-invite unstyled horizontal">
          <li class="nobody">Ninguno</li>
        </ul>
        
        <p><b>!Nuevos amigos!</b> También podes invitar a tus amigos no registrados escribiendo sus emails en este campo y separándolos por una coma.</p>
        <%= f.input :emails, :as => :text, :label => false, :placeholder => 'Emails', :input_html => { :rows => 1, :class => 'autogrow' } %>

        <p>Escribí un mensaje de invitación para tus amigos.</p>
        <%= f.input :comment, :as => :text, :placeholder => 'Mensaje', :label => false, :required => false, :input_html => { :rows => 3, :class => 'autogrow' } %>
      </div>
      <div class="modal-footer">
        <%= f.submit "Invitar!", :class => 'btn btn-primary pull-right' %>
      </div>
    <% end %>
  </div>
</div>

app/views/matches/_match_tabs.html.erb
<ul class="nav nav-tabs nav-match">

  <% unless Match.upcoming(current_user).include?(@match) or Match.pending_review(current_user).include?(@match) %>
    <li class="active">
      <%= link_to match_path(@match) do %>
        Partido
      <% end -%>
    </li>
  <% end -%>
  <% Match.pending_review(current_user).each do |match| %>
    <li class="<%= "active" if @match == match -%>">
      <%= link_to match_path(match) do %>
        <%= match_date(match) %>
      <% end -%>
    </li>
  <% end -%>
  <% Match.upcoming(current_user).each do |match| %>
    <li class="<%= "active" if @match == match -%>">
      <%= link_to match_path(match) do %>
        <%= match_date(match) %>
      <% end -%>
    </li>
  <% end -%>

</ul>

app/views/matches/_players.html.erb
<div class="span9">
  <div class="stadium">
    <% match.users.starting(match.number_of_players_in_stadium).each_with_index do |player, index| %>
      <div class="player number-<%= index %>">
        <%= link_to image_tag(player.avatar.url(:thumb)), player %>
      </div>
    <% end %>
  </div>
</div>

<div class="span9">
  <h4>Jugadores al banco</h4>
  <ul class="substitutes">
    <% match.users.substitutes(match.number_of_players_in_stadium).each_with_index do |player, index| %>
      <li class="user" data-user-id="<%= player.id %>"><%= link_to image_tag(player.avatar.url(:thumb)), player, :title => player.name %></li>
    <% end %>
  </ul>
</div>

<div class="span9">
  <div class="invited">
    <h4>Pendientes de confirmacion</h4>
    <ul class="undecided">
      <% match.users.undecided.each_with_index do |user, index| %>
        <li class="user" data-user-id="<%= user.id %>"><%= link_to image_tag(user.avatar.url(:thumb)), user, :title => user.name %></li>
      <% end %>
    </ul>
    <h4>Despreciables que no van</h4>
    <ul class="not-going">
      <% match.users.not_going.each do |user| %>
        <li class="user" data-user-id="<%= user.id %>"><%= link_to image_tag(user.avatar.url(:thumb)), user, :title => user.name %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/matches/_rsvp.html.erb
<% invite = current_user.invitation_to_play(@match) %>

<div class="wrapper invite-confirm">
  <%= render :partial => 'rsvp_accepted', :locals => { :invite => invite }  if invite.accepted? -%>
  <%= render :partial => 'rsvp_declined', :locals => { :invite => invite }  if invite.declined? -%>
  <%= render :partial => 'rsvp_pending', :locals => { :invite => invite }  if invite.pending? -%>
</div>

app/views/matches/_rsvp_declined.html.erb
<div class="title rsvp declined">
  <h2><%= t :not_going, :scope => [:messages, :match] %></h2>
</div>

<div class="input">
  <p>
    <%= t :you_are_not_going, :scope => [:messages, :match] %>
  </p>
  <%= link_to accept_invitations_to_play_url(invite), :class => 'choose' do %>
    <%= image_tag 'icn_yes_s.png' %> <%= t(:change_mind_going, :scope => [:actions]) %>
  <% end %>
</div>

app/views/matches/_rsvp_pending.html.erb
<div class="title rsvp pending">
  <h2><%= t :confirm, :scope => [:messages, :match] %></h2>
</div>

<div class="input">
  <p><%= t(:someone_invited_you_are_you_going, :scope => [:messages, :match], :host_name => "<span class='host-name'>#{h(invite.host.name)}</span>").html_safe %></p>
  <%= link_to accept_invitations_to_play_url(invite), :class => 'choose' do %>
    <%= image_tag 'icn_yes_s.png' %> <%= t :i_am_going, :scope => [:actions] %>
  <% end -%>
  <%= link_to decline_invitations_to_play_url(invite), :class => 'choose' do %>
    <%= image_tag 'icn_no_s.png' %> <%= t :i_am_not_going, :scope => [:actions] %>
  <% end -%>
</div>

app/views/matches/_thanks_for_invite_to_play.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal"></button>
  <h3>Aleluya hermanos!</h3>
</div>
<div class="modal-body">
  <div class="row">
    <div class="span3">
      <%= link_to image_tag("ilus_iso_fh.png"), root_path %>
    </div>
    <div class="span3">
      <h4 class="confirmation-title">Felicitaciones!!!</h4>
      <p class="message">Tu invitacion se ha enviado correctamente</p>
      <p>Fobal Hero. Quiero Jugar!</p>
    </div>
  </div>
</div>

app/views/matches/comments.js.erb
<% if @comments.any? %>
  $('#comments').prepend('<div class="show-later"><% @comments.each do |comment| %><%=j raw(render(:partial => 'comment', :locals => { :comment => comment, :comment_side => calculate_comment_side(comment, @prev_comment) })) %><% end %></div>');
  $('.show-later').slideDown('slow');
  FobalHero.matches.action_show.restartCommentRefresh();
<% end %>

app/views/matches/index.html.erb
<div class="title match34">
  <h2>Historial de juego</h2>
</div>

<div class="history-content">

  <h3>Partidos que se vienen</h3>
  <table class="table">

  <% @upcoming_matches.each do |match| %>
    <tr>
      <td class="teams-score">
      <%= match.team_one_proposed_score %>
      <%= image_tag 'shields/shield_01.png' %>
      <strong>VS</strong>
      <%= image_tag 'shields/shield_02.png' %>
      <%= match.team_two_proposed_score %>
      </td>

      <td class="date"><%= l(match.play_at, :format => :short) unless match.play_at.nil? %></td>
      <td class="type"><%= t match.match_type, :scope => [:activerecord, :attributes, :match, :match_type_values], :default => "" %></td>
      <td class="stadium-name"><%= match.stadium_name %></td>
      <td class="link"><%= link_to "Ver partido", match %></td>
    </tr>
  <% end %>
  </table>

  <h3>Partidos a evaluar</h3>
  <table class="table">

  <% @recent_matches.each do |match| %>
    <tr>
      <td class="teams-score">
      <%= match.team_one_proposed_score %>
      <%= image_tag 'shields/shield_01.png' %>
      <strong>VS</strong>
      <%= image_tag 'shields/shield_02.png' %>
      <%= match.team_two_proposed_score %>
      </td>
      
      <td class="date"><%= l(match.play_at, :format => :short) unless match.play_at.nil? %></td>
      <td class="type"><%= t match.match_type, :scope => [:activerecord, :attributes, :match, :match_type_values], :default => "" %></td>
      <td class="stadium"><%= match.stadium_name %></td>
      <td class="link"><%= link_to "Ver partido", match %></td>
    </tr>
  <% end %>
  </table>

  <h3>Partidos jugados</h3>
  <table class="table">

  <% @past_matches.each do |match| %>
    <tr>
      <td class="teams-score">
      <%= match.team_one_proposed_score %>
      <%= image_tag 'shields/shield_01.png' %>
      <strong>VS</strong>
      <%= image_tag 'shields/shield_02.png' %>
      <%= match.team_two_proposed_score %>
      </td>
      
      <td class="date"><%= l(match.play_at, :format => :short) unless match.play_at.nil? %></td>
      <td class="type"><%= t match.match_type, :scope => [:activerecord, :attributes, :match, :match_type_values], :default => "" %></td>
      <td class="stadium-name"><%= match.stadium_name %></td>
      <td class="link"><%= link_to "Ver partido", match %></td>
    </tr>
  <% end %>
  </table>

  <% content_for :sidebar do %>
    <!-- <p>Partidos que tenes que calificar</p> -->
        <%= render :partial => 'users/pending_invitation' if Match.waiting_response(current_user).any? %>
  <% end %>

</div>

app/views/matches/post_comment.js.erb
$('#new_comment textarea').val("");
$('#new_comment textarea').focus();
FobalHero.matches.action_show.fetchComments();

app/views/matches/show.html.erb
<%= render :partial => 'match_tabs' %>

<div class="match-wrapper"><!-- START MATCH WRAPPER -->

  <%= simple_form_for(@match, :html => { :id => 'match_form', :data => { :id => @match.id }}) do |f| %>
    <div class="title match34">
      <h2><%= t :new, :scope => [:titles, :match] %></h2>
      <div class="action">
        <%= link_to "Avisar", notify_changes_match_path(@match),
          :class => "#{@match.pending_notification? ? 'active' : 'disabled' } btn btn-primary",
          :id => 'notify_changes' unless @match.already_played?%>
        <%= f.submit "Guardar", :class => 'btn btn-primary' unless @match.already_played? -%>
      </div>
    </div>
    <% if @match.errors.any? %>
      <div id="error_explanation">
        <h2>Che, hay algunos problemas con los datos</h2>
        <ul>
          <% @match.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <%= display_details_for @match %>
      <%= render :partial => 'players', :locals => { :match => @match } %>
    </div>

  <% end %>

</div><!-- END MATCH WRAPPER -->

<div class="row">
  <div class="span9">
    <div id="new_comment_wrapper">
      <p><strong><%= current_user.name %></strong><br/>Comenta algo sobre el partido.</p>
      <%= simple_form_for @new_comment, :url => post_comment_match_path(@match), :remote => true do |f| %>
        <%= f.input :body, :label => false, :as => :text, :input_html => { :rows => 1 } %>
      <% end %>
    </div>
    <div id="comments"></div>
  </div>
</div>

<!-- Start modal window -->
<%= render :partial => 'invite_to_play_popup' %>
<!-- End modal window -->

<!-- Start sidebar -->
<%= render :partial => 'sidebar' %>
<!-- End sidebar -->