config/routes.rb
FobalHero::Application.routes.draw do

  resources :friendships

  resources :stadiums

  post 'notifications/read'

  resources :invitations_to_register, :only => [:create] do
    member do
      get 'accept'
    end
  end

  resources :invitations_to_play, :only => [] do
    member do
      get 'accept'
      get 'decline'
    end
  end

  resources :matches, :except => [:destroy, :edit] do
    member do
      post :notify_changes
      post :invite_to_play
      post :post_comment
      get :comments
      post :i_played, :controller => :surveys
      post :i_didnt_play, :controller => :surveys
      post :i_agree_score, :controller => :surveys
      post :i_dont_agree_score, :controller => :surveys
      post :set_my_goals, :controller => :surveys
      post :set_score, :controller => :surveys
      post :set_stadium_stars, :controller => :surveys

      post :badge, :controller => :match_survey_badges, :action => :create
      delete :badge, :controller => :match_survey_badges, :action => :destroy
    end
  end

  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :confirmations => 'confirmations',
    :passwords => 'passwords',
    :registrations => 'registrations'
  }
  resources :users, :only => [:edit, :update, :show]
  match '/admin/users' => 'users#index'
  match 'profile' => 'users#edit'

  devise_scope :user do
    get 'login', :to => 'devise/sessions#new'
    get 'logout', :to => 'devise/sessions#destroy'
  end

  authenticated do
    root :to => 'home#authenticated'
  end

  post 'register', :to => 'home#register'

  root :to => 'home#public'

end

app/models/stadium.rb
class Stadium < ActiveRecord::Base
  attr_accessible :description, :lat, :lon, :name, :phone_one, :phone_two, :address, :logo, :website, :email
  
  has_attached_file :logo,
    :styles => {
      :medium => "300x300>",
      :thumb => "50x50#",
      :mini => "24x24#"
    }

  validates :name, :description, :phone_one, :presence => true
  validates_format_of :email, :with => /@/

  has_many :matches
end

app/controllers/stadiums_controller.rb
class StadiumsController < ApplicationController
  # GET /stadiums
  # GET /stadiums.json
  def index
    @stadiums = Stadium.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stadiums }
    end
  end

  # GET /stadiums/1
  # GET /stadiums/1.json
  def show
    @stadium = Stadium.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stadium }
    end
  end

  # GET /stadiums/new
  # GET /stadiums/new.json
  def new
    @stadium = Stadium.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stadium }
    end
  end

  # GET /stadiums/1/edit
  def edit
    @stadium = Stadium.find(params[:id])
  end

  # POST /stadiums
  # POST /stadiums.json
  def create
    @stadium = Stadium.new(params[:stadium])

    respond_to do |format|
      if @stadium.save
        format.html { redirect_to @stadium, notice: 'Stadium was successfully created.' }
        format.json { render json: @stadium, status: :created, location: @stadium }
      else
        format.html { render action: "new" }
        format.json { render json: @stadium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stadiums/1
  # PUT /stadiums/1.json
  def update
    @stadium = Stadium.find(params[:id])

    respond_to do |format|
      if @stadium.update_attributes(params[:stadium])
        format.html { redirect_to @stadium, notice: 'Stadium was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stadium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stadiums/1
  # DELETE /stadiums/1.json
  def destroy
    @stadium = Stadium.find(params[:id])
    @stadium.destroy

    respond_to do |format|
      format.html { redirect_to stadiums_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stadiums_helper.rb
module StadiumsHelper
  def website_for_stadium(stadium)
    link_to stadium.website, stadium.website if stadium.website.present?
  end

  def description_for_stadium(stadium)
    simple_format(truncate(stadium.description, :length => 100))
  end
end

app/views/stadiums/_form.html.erb
<%= simple_form_for(@stadium) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_one %>
    <%= f.input :phone_two %>
    <%= f.input :website %>
    <%= f.input :email %>
    <%= f.input :description %>
    <%= f.input :lat %>
    <%= f.input :lon %>
    <%= f.input :logo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stadiums/edit.html.erb
<h1>Editing stadium</h1>

<%= render 'form' %>

<%= link_to 'Show', @stadium %> |
<%= link_to 'Back', stadiums_path %>

app/views/stadiums/index.html.erb
<div class="stadiums-wrapper">

    <table class="table">
      <tr>
        <th class="span1"></th>
        <th><%= Stadium.human_attribute_name :name %></th>
        <th><%= Stadium.human_attribute_name :phone_one %></th>
        <th><%= Stadium.human_attribute_name :address %></th>
        <th><%= Stadium.human_attribute_name :website %></th>
        <th><%= Stadium.human_attribute_name :email %></th>
        <th><%= Stadium.human_attribute_name :description %></th>
      </tr>

    <% @stadiums.each do |stadium| %>
      <tr>
        <td><%= link_to image_tag(stadium.logo.url(:thumb)), stadium_path(stadium) %></td>
        <td><%= link_to stadium.name, stadium_path(stadium) %></td>
        <td><%= stadium.phone_one %> <%= stadium.phone_two %></td>
        <td><%= stadium.address %></td>
        <td><%= website_for_stadium(stadium) %></td>
        <td><%= stadium.email %></td>
        <td><%= description_for_stadium(stadium) %></td>
      </tr>
    <% end %>
    </table>
</div>

<%= link_to 'New Stadium', new_stadium_path %>

app/views/stadiums/new.html.erb
<h1>New stadium</h1>

<%= render 'form' %>

<%= link_to 'Back', stadiums_path %>

app/views/stadiums/show.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?sensor=false" %>

  <script type="text/javascript">
    $(document).ready(function(){
      var stadium = new google.maps.LatLng(<%= @stadium.lat %>,<%= @stadium.lon %>);
      var mapOptions = {
        zoom: 15,
        center: stadium,
        scrollwheel: false,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      }
      var map = new google.maps.Map(document.getElementById('map'), mapOptions);

      var marker = new google.maps.Marker({
        position: stadium,
        id: '1',
        title: "<%= @stadium.name %>",
        cursor: 'pointer',
        flat: false,
        map: map
      });
      // ,icon: new google.maps.MarkerImage('/assets/placemark.png',
      //   new google.maps.Size(32, 35),
      //   new google.maps.Point(0, 0),
      //   new google.maps.Point(32 / 2, 35),
      //   new google.maps.Size(32, 35))
    })
  </script>
<% end %>

<p>
  <b><%= Stadium.human_attribute_name :name %>:</b>
  <%= @stadium.name %>
</p>

<p>
  <b><%= Stadium.human_attribute_name :ranking %>:</b>
  estrellas
</p>

<p>
  <b><%= Stadium.human_attribute_name :address %>:</b>
  <%= @stadium.address %>
</p>

<p>
  <b><%= Stadium.human_attribute_name :phone_one %>:</b>
  <%= @stadium.phone_one %>
</p>

<p>
  <b><%= Stadium.human_attribute_name :phone_two %>:</b>
  <%= @stadium.phone_two %>
</p>

<p>
  <b><%= Stadium.human_attribute_name :website %>:</b>
  <%= link_to @stadium.website, @stadium.website if @stadium.website.present? %>
</p>

<p>
  <b><%= Stadium.human_attribute_name :email %>:</b>
  <%= mail_to @stadium.email  %>
</p>

<p>
  <b><%= Stadium.human_attribute_name :description %>:</b>
  <%= @stadium.description %>
</p>

<p>
  <%= image_tag @stadium.logo.url(:medium) %>
</p>

<div id="map"></div>


<%= link_to 'Edit', edit_stadium_path(@stadium) %> |
<%= link_to 'Back', stadiums_path %>